name: Build Container for mybinder.org

on:
  # Until this repo is in production, we omit the automatic trigger on Binder
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
